//login types
export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGIN_CLICKED = 'LOGIN_CLICKED';
export const LOGIN_PHONE_CHANGED = 'LOGIN_PHONE_CHANGED';
export const LOGIN_PASSWORD_CHANGED = 'LOGIN_PASSWORD_CHANGED';
export const LOGIN_SHOW_PASSWORD = 'LOGIN_SHOW_PASSWORD';

//register types
export const FIRST_NAME_CHANGED = 'FIRST_NAME_CHANGED';
export const LAST_NAME_CHANGED = 'LAST_NAME_CHANGED';
export const EMAIL_CHANGED = 'EMAIL_CHANGED';
export const PHONE_CHANGED = 'PHONE_CHANGED';
export const PASSWORD_CHANGED = 'PASSWORD_CHANGED';
export const REGISTER_USER = 'REGISTER';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const REGISTER_CLICKED = 'REGISTER_CLICKED';
export const REGISTER_SHOW_PASSWORD = 'REGISTER_SHOW_PASSWORD';

//chat types
export const CREATE_CONVERSATION = 'CREATE_CONVERSATION';
export const FETCH_CONVERSATIONS_LIST = 'FETCH_CONVERSATIONS';
export const FETCH_CONVERSATIONS_LIST_SUCCESS = 'FETCH_CONVERSATIONS_SUCCESS';
export const FETCH_CONVERSATIONS_LIST_FAIL = 'FETCH_CONVERSATIONS_FAIL';
export const TOGGLE_FETCHING_CONVERSATIONS = 'TOGGLE_FETCHING_CONVERSATIONS';
export const CREATE_CONVERSATION_FAIL = 'CREATE_CONVERSATION_FAIL';
export const CREATE_CONVERSATION_SUCCESS='CREATE_CONVERSATION_SUCCESS';
export const CREATE_CONVERSATION_ATTEMPTING='CREATE_CONVERSATION_ATTEMPTING';
export const CREATE_CONVERSATION_PHONE_CHANGED = 'CREATE_CONVERSATION_PHONE_CHANGED';
//individual conversation types
export const OPEN_CONVERSATION = 'OPEN_CONVERSATION';
export const FETCH_MESSAGES = 'FETCH_MESSAGES';
export const FETCH_MESSAGES_FAIL = 'FETCH_MESSAGES_FAIL';
export const FETCH_MESSAGES_SUCCESS = 'FETCH_MESSAGES_SUCCESS';
//messsage types
export const SEND_MESSAGE = 'SEND_MESSAGE';
export const ENCRYPT_MESSAGE = 'ENCRYPT_MESSAGE';
export const DECRYPT_MESSAGE = 'DECRYPT_MESSAGE';
export const SEND_MESSAGE_FAIL = 'SEND_MESSAGE_FAIL';
export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS';
export const MESSAGE_CONTENT_CHANGED = 'MESSAGE_CONTENT_CHANGED';
//crypto types