//login types
const LOGIN = 'LOGIN';
const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
const LOGIN_FAIL = 'LOGIN_FAIL';
const LOGIN_CLICKED = 'LOGIN_CLICKED';

//register types
const FIRST_NAME_CHANGED = 'FIRST_NAME_CHANGED';
const LAST_NAME_CHANGED = 'LAST_NAME_CHANGED';
const EMAIL_CHANGED = 'EMAIL_CHANGED';
const PHONE_CHANGED = 'PHONE_CHANGED';
const PASSWORD_CHANGED = 'PASSWORD_CHANGED';
const CONFIRM_PASSWORD_CHANGED = 'CONFIRM_PASSWORD_CHANGED';
const REGISTER_USER = 'REGISTER';
const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
const REGISTER_FAIL = 'REGISTER_FAIL';
const REGISTER_CLICKED = 'REGISTER_CLICKED';

//chat types

//messsage types

//crypto types

export {
    LOGIN,
    LOGIN_SUCCESS,
    LOGIN_FAIL,
    LOGIN_CLICKED,
    REGISTER_USER,
    REGISTER_SUCCESS,
    REGISTER_FAIL,
    REGISTER_CLICKED
};